name: Package check
on: [push, pull_request, workflow_dispatch]
jobs:
  check:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} R ${{ matrix.r-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022 ] # [ macos-13, macos-14, ubuntu-22.04, windows-2022 ]
        r-version: [ release ] # [ release, devel ]
    steps:
      - uses: actions/checkout@v4
      - name: Install R
        uses: s-u/R-actions/install@v2
        with:
          r-version: ${{ matrix.r-version }}
          tools: base
      - name: Make sure pkg-check action can see other packages on Windows
        run: |
          if [ ${{ runner.os }} = Windows ]; then
            echo "R_LIBS_USER=$(pwd)\Rlib" >> $GITHUB_ENV
          fi
      - name: Install tinytex
        uses: s-u/R-actions/tinytex@v1
      - name: Checkout {dvi}
        uses: actions/checkout@v4
        with: 
          repository: pmur002/dvi
          path: dvi
      - name: Install {dvi} 
        run: |
          Rscript -e 'install.packages("hexView", repos="https://cloud.r-project.org")'
          Rscript -e 'install.packages("dvi", type="source", repos=NULL)'
      - name: Install ttx system deps on macOS
        if: runner.os == 'macOS'
        run: |
          brew install fonttools
          brew install fontforge
      - name: Install ttx system deps on Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          pip install fonttools
          choco install fontforge
          echo 'C:\Program Files (x86)\FontForgeBuilds\' >> $GITHUB_PATH
      - name: Checkout {ttx}
        uses: actions/checkout@v4
        with: 
          repository: pmur002/ttx
          path: ttx
      - name: Install {ttx}
        run: |
          Rscript -e 'install.packages("xml2", repos="https://cloud.r-project.org")'
          Rscript -e 'install.packages("ttx", type="source", repos=NULL)'
      - uses: s-u/R-actions/pkg-check@v2
        with:
          debian-deps: 
            fonttools
            fontforge
          check-flags: --as-cran
