name: Package check
on: [push, pull_request, workflow_dispatch]
jobs:
  check:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} R ${{ matrix.r-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ] # [ macos-13, macos-14, ubuntu-22.04, windows-2022 ]
        r-version: [ devel ] # [ release, devel ]
    steps:
      - uses: actions/checkout@v4
      - name: Install R
        uses: s-u/R-actions/install@v2
        with:
          r-version: ${{ matrix.r-version }}
          tools: base
      - name: Install tinytex
        uses: s-u/R-actions/tinytex@v1
      - name: Checkout {dvi}
        uses: actions/checkout@v4
        with: 
          repository: pmur002/dvi
          path: dvi
      - name: Install {dvi}
        run: |
          R CMD build dvi
          ls
          R CMD INSTALL dvi*.tar.gz
      - name: Install ttx system deps on macOS
        if: runner.os == 'macOS'
        run: |
          brew install fonttools
          brew install fontforge
      - name: Install ttx system deps on Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          pip install fonttools
          choco install fontforge
          echo 'C:\Program Files (x86)\FontForgeBuilds\' >> $GITHUB_PATH
      - name: Checkout {ttx}
        uses: actions/checkout@v4
        with: 
          repository: pmur002/ttx
          path: ttx
      - name: Install {ttx}
        run: |
          R CMD build ttx
          R CMD INSTALL ttx*.tar.gz
      - uses: s-u/R-actions/pkg-check@v2
        with:
          pkg-path: main
          debian-deps: 
            fonttools
            fontforge
          check-flags: --as-cran
