name: Package check
on: [push, pull_request, workflow_dispatch]
jobs:
  check:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} R ${{ matrix.r-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, ubuntu-22.04, windows-2022 ] # [ macos-13, macos-14, ubuntu-22.04, windows-2022 ]
        r-version: [ release ] # [ release, devel ]
    steps:
      - uses: actions/checkout@v4
      - name: Install R
        uses: s-u/R-actions/install@v2
        with:
          r-version: ${{ matrix.r-version }}
          tools: base
      - name: Install tinytex
        uses: s-u/R-actions/tinytex@v1
      - name: Checkout {dvi}
        uses: actions/checkout@v4
        with: 
          repository: pmur002/dvi
          path: dvi
      - name: Install {dvi} 
        run: |
          Rscript -e 'install.packages("hexView", repos="https://cloud.r-project.org", dependencies=TRUE)'
          Rscript -e 'install.packages("dvi", type="source", repos=NULL)'
        shell: bash
      - name: Install ttx system deps on macOS
        if: runner.os == 'macOS'
        run: |
          brew install fonttools
          brew install fontforge
      - name: Install ttx system deps on Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          pip install fonttools
          choco install fontforge
          echo 'C:\Program Files (x86)\FontForgeBuilds\' >> $GITHUB_PATH
      - name: Checkout {ttx}
        uses: actions/checkout@v4
        with: 
          repository: pmur002/ttx
          path: ttx
      - name: Install {ttx}
        run: |
          Rscript -e 'install.packages("xml2", repos="https://cloud.r-project.org", dependencies=TRUE)'
          Rscript -e 'install.packages("ttx", type="source", repos=NULL)'
        shell: bash
      - uses: s-u/R-actions/pkg-check@v2
        with:
          debian-deps: 
            fonttools
            fontforge
          check-flags: --as-cran
      - name: Artifact set up
        if: failure()
        run: |
          if [ ${{ runner.os }} = Windows ] ; then
            TDIR=`cygpath -m $GITHUB_WORKSPACE/..`
          else
            TDIR=$(cd $GITHUB_WORKSPACE/.. && pwd)
          fi
          echo "TOP_DIR=$TDIR" >> $GITHUB_ENV
        shell: bash
      - name: Upload check results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-r-${{ matrix.r-version }}-results
          path: ${{ env.TOP_DIR }}/latex.Rcheck/

